//
//  WNChapter.swift
//  WebNovel
//
//  Created by Jiachen Ren on 6/15/19.
//  Copyright © 2019 Jiachen Ren. All rights reserved.
//

import Foundation

class WNChapter: Serializable, CustomStringConvertible {
    typealias ManagedObject = Chapter
    
    // Basic info
    var url: String?
    var chapter: String
    
    // Raw html content of the chapter
    var rawHtml: String?
    
    // Sanitized chapter infomation generated by a host-specific parser
    var date: String?
    var title: String?
    var textContent: String?

    // Article contains relevant reader's info generated by a
    // non-host-specific, generic parser, namely Readability.js
    var article: Article?
    
    /// Id of the chapter
    var id: Int
    
    init(url: String, chapter: String, id: Int) {
        self.url = url
        self.chapter = chapter
        self.id = id
    }
    
    var description: String {
        return """
        ID: \(id)
        Chapter: \(chapter)
        Link: \(url ?? "N/A")
        Title: \(title ?? "N/A")
        Date: \(date ?? "N/A")
        Text Content: \(textContent ?? "N/A")
        """
    }
}
